import { standardAttackModifierFactory } from './variants/standard'
import { finesseAttackModifierFactory } from './variants/finesse'
import { Attack, AttackModifierFunc, AttackModifierFuncFactory, AttackModifierRequiredData } from './types'
import { default as calculateFeatMod, CalculateFeatModRequiredData } from './feat-mod'
import { default as calculateBaseMod, } from './base-mod'