export { standardAttackModifierFactory } from './variants/standard'
export { finesseAttackModifierFactory } from './variants/finesse'
export type { Attack, AttackModifierFunc, AttackModifierFuncFactory, AttackModifierRequiredData } from './types'
export { default as calculateFeatMod } from './feat-mod'
export type { CalculateFeatModRequiredData } from './feat-mod'
export { default as calculateBaseMod } from './base-mod'
